/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SharedMemory */

#ifndef _Included_SharedMemory
#define _Included_SharedMemory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SharedMemory
 * Method:    AlocWeaveSharedBuffer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SharedMemory_AlocWeaveSharedBuffer
  (JNIEnv *, jclass);

/*
 * Class:     SharedMemory
 * Method:    GetSignalArray
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_SharedMemory_GetSignalArray
  (JNIEnv *, jclass);

/*
 * Class:     SharedMemory
 * Method:    FreeWeaveSharedBuffer
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SharedMemory_FreeWeaveSharedBuffer
  (JNIEnv *, jclass);

/*
 * Class:     SharedMemory
 * Method:    ReleaseProcess
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_SharedMemory_ReleaseProcess
  (JNIEnv *, jclass, jint);

/*
 * Class:     SharedMemory
 * Method:    WaitForProcess
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_SharedMemory_WaitForProcess
  (JNIEnv *, jclass, jint);

/*
 * Class:     SharedMemory
 * Method:    CreatePythonProcess
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_SharedMemory_CreatePythonProcess
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
