/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SharedMemory */

#ifndef _Included_SharedMemory
#define _Included_SharedMemory
#ifdef __cplusplus
extern "C" {
#endif
#undef SharedMemory_PROCESS_SLEEPING
#define SharedMemory_PROCESS_SLEEPING 0L
#undef SharedMemory_PROCESS_AQUIRED
#define SharedMemory_PROCESS_AQUIRED 1L
#undef SharedMemory_PROCESS_FINISHED
#define SharedMemory_PROCESS_FINISHED 2L
/*
 * Class:     SharedMemory
 * Method:    Init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SharedMemory_Init
  (JNIEnv *, jclass);

/*
 * Class:     SharedMemory
 * Method:    GetSignalArray
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_SharedMemory_GetSignalArray
  (JNIEnv *, jclass);

/*
 * Class:     SharedMemory
 * Method:    DeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SharedMemory_DeInit
  (JNIEnv *, jclass);

/*
 * Class:     SharedMemory
 * Method:    ReleaseProcess
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_SharedMemory_ReleaseProcess
  (JNIEnv *, jclass, jint);

/*
 * Class:     SharedMemory
 * Method:    WaitForProcess
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_SharedMemory_WaitForProcess
  (JNIEnv *, jclass, jint);

/*
 * Class:     SharedMemory
 * Method:    GetProcessesOutput
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_SharedMemory_GetProcessesOutput
  (JNIEnv *, jclass);

/*
 * Class:     SharedMemory
 * Method:    CreatePythonProcess
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_SharedMemory_CreatePythonProcess
  (JNIEnv *, jclass, jstring);

/*
 * Class:     SharedMemory
 * Method:    isProcessAlive
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_SharedMemory_isProcessAlive
  (JNIEnv *, jclass, jlong);

/*
 * Class:     SharedMemory
 * Method:    ReaderThreadStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SharedMemory_ReaderThreadStart
  (JNIEnv *, jclass);

/*
 * Class:     SharedMemory
 * Method:    ReaderThreadStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_SharedMemory_ReaderThreadStop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
