/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class WeaveNativeImpl */

#ifndef _Included_WeaveNativeImpl
#define _Included_WeaveNativeImpl
#ifdef __cplusplus
extern "C" {
#endif
#undef WeaveNativeImpl_PROCESS_SLEEPING
#define WeaveNativeImpl_PROCESS_SLEEPING 0L
#undef WeaveNativeImpl_PROCESS_ACQUIRED
#define WeaveNativeImpl_PROCESS_ACQUIRED 1L
#undef WeaveNativeImpl_PROCESS_FINISHED
#define WeaveNativeImpl_PROCESS_FINISHED 2L
/*
 * Class:     WeaveNativeImpl
 * Method:    Init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_WeaveNativeImpl_Init
  (JNIEnv *, jobject);

/*
 * Class:     WeaveNativeImpl
 * Method:    GetSignalArray
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_WeaveNativeImpl_GetSignalArray
  (JNIEnv *, jobject);

/*
 * Class:     WeaveNativeImpl
 * Method:    DeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_WeaveNativeImpl_DeInit
  (JNIEnv *, jobject);

/*
 * Class:     WeaveNativeImpl
 * Method:    ReleaseProcess
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_WeaveNativeImpl_ReleaseProcess
  (JNIEnv *, jobject, jint);

/*
 * Class:     WeaveNativeImpl
 * Method:    WaitForProcess
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_WeaveNativeImpl_WaitForProcess
  (JNIEnv *, jobject, jint);

/*
 * Class:     WeaveNativeImpl
 * Method:    GetProcessesOutput
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_WeaveNativeImpl_GetProcessesOutput
  (JNIEnv *, jobject);

/*
 * Class:     WeaveNativeImpl
 * Method:    CreatePythonProcess
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_WeaveNativeImpl_CreatePythonProcess
  (JNIEnv *, jobject, jstring);

/*
 * Class:     WeaveNativeImpl
 * Method:    isProcessAlive
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_WeaveNativeImpl_isProcessAlive
  (JNIEnv *, jobject, jlong);

/*
 * Class:     WeaveNativeImpl
 * Method:    ReaderThreadStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_WeaveNativeImpl_ReaderThreadStart
  (JNIEnv *, jobject);

/*
 * Class:     WeaveNativeImpl
 * Method:    ReaderThreadStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_WeaveNativeImpl_ReaderThreadStop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
